apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-server
  name: node-svc
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    app: node-server
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: node-ingress
spec:
  tls:
  - hosts:
    - ui.ingress.https-test.cpet.shoot.canary.k8s-hana.ondemand.com
    secretName: tls-secret
  rules:
  - host: ui.ingress.https-test.cpet.shoot.canary.k8s-hana.ondemand.com
    http:
      paths:
      - backend:
          serviceName: node-svc
          servicePort: 8080
